# S1 후속 보고 - 보안 · 경제 (2026-09-27 · 묶음 "S1 후속 → BR1-4a → BR1-4b" 파트 0)

지시 = 파트 0 (0-1 ~ 0-7). 검증 = COMMON §7-1(이번 수정만 · VerifyOnly). 리뷰어 서브에이전트 2회(전체 diff · 공중 정체 검사). **SAVE_VERSION 변경 없음** · **place 저장 불필요**.

## 결과 표

| # | 항목 | 결과 | 근거 |
|---|---|---|---|
| 0-1 | G2a(나) 체인 첫머리 미적발 원인 | **원인 좁힘 + 새 틈 막음** · 검증 항목 자체는 X(아래) | 판정 흔적: 유예 0 · 예외 0 · 꺼짐 false · 서버가 본 발 +17.3 ~ 20.5 < 허용 22.38 = 서버는 본 대로 옳게 판정. 같은 동작을 체인 뒤에 하면 목표 도달 · 0.95초 되돌림 |
| 0-1 추가 | 허용 아래 "띄워 두기" 틈 | **막음**(공중 정체 검사) | 흔적이 보여 준 것: 발 +17.3에서 6초 떠 있어도 아무 검사가 안 걸렸다 = 실제 부정 사용자가 쓸 수 있다 → 5초 넘게 안 내려가면 되돌림 |
| 0-2 | 공속 상한 = 버프 포함 최종 값 ×2.5 | **구현 · 기본 꺼짐(결정 대기)** | 켜면 EconSim 상위 1% 25,300 **1,968 → 2,354시간(+19.6%)** - ±3% 초과 |
| 0-2 | 다른 스탯 같은 방식인지 전수 | 확인 | 아래 [2] 표 |
| 0-2 | 직업 DPS 재측정 | 바뀐 곳 = 활 최고 속도 구간만 | 아래 [2] 표 |
| 0-3 | 상한 없는 4종 | **최종 피해 +105%만 적용** · 나머지 3종 미적용(보고) | 제안값이 도달 최대보다 낮아 실제로 잘린다 |
| 0-4 | 발사 허가 수평 속도 | **보스 발사만 400/s** · 발판 = 설계 × 1.25 · 열매 · 붙잡기 = 걷기 | 나무 발사 30/30 되돌림 0 · 설계 최대 57.3/s |
| 0-4 | 지연 0.25 되돌림 0 | O(실측 · 합성) | 엘리베이터 상승 · 실제 낙하 되돌림 0 · 합성 점프대 2초 되돌림 0(대조군 되돌림 있음) |
| 0-5 | `/ops stats` 라이브 · 종료 요약 저장 | O | `/ops stats` · `/ops stats all`(저장된 서버 요약 합) · BindToClose |
| 0-6 | 비밀 둥지 단서 이름 중립화 | O(리뷰 반영으로 강화) | 옛 이름 0 · C 전용 모델 이름 0 · 단서 속성 0 · 번개 문 1 · 반딧불 11(동작 불변) |
| 0-7 | 지연 0.25 낙하 실측 | 판정 경로 도달 O · 피해 적용 **미확인** | 실제 57 낙하 → 서버 궤적 55 · 스폰이 허브 나무 구역이라 `excluded:tree` |
| 0-7 | 봉투 초과 리더보드 보류 실제 판정 | O | 실제 `Leaderboard.eligibility` → `velocity_hold` / 합법 시간 → `ok` |

## [1] 0-1 G2a(나) · 공중 정체

- 계측(HeightGuard `st.trace` - 검증이 켤 때만): Play 1 · 2 · 3 모두 체인 첫머리(서버 시작 약 12초 뒤)에 띄워 두기(AlignPosition 목표 허용 + 3 → + 10)가 **발 +17 ~ 20에서 멈춤**. 판정 흔적은 전부 `ok`(유예 0.0 · 예외 0.0 · 꺼짐 false · 발 < 허용).
- 같은 Play에서 체인이 끝난 뒤 같은 동작(넉백 → 띄워 두기 · 네 방향)은 목표 +32까지 오르고 **서버가 0.95초에 되돌림** - 서버 판정 · 폴링은 정상.
- 확인해 지운 가설: 천장(스폰 위 충돌 파트 없음) · 도착 대기 `ArrivalHold`(지면이 40 안) · 태초 장갑 붙잡기(`LedgeUsed` 안 켜짐) · 위치 복제 정지(정지 표본 3/120 - 정지 아님).
- **결론: 서버 틈은 아니지만, 흔적이 다른 틈을 보여 줬다** - 허용 높이 아래에서 떠 있기만 하면 몇 초든 아무 검사도 걸리지 않는다(부정 사용자가 허용 아래 높이로 떠서 이동 · 구덩이 건너기). → **공중 정체 검사**(`HeightGuard.evaluate` · `MovementConfig.heightGuard.stallSeconds 5` · `stallDropStuds 1`): 원거리 공중 정지(서버 `AirState`) · 설계 체공 안의 발사 허가 · 붙잡힘 예외 · 순간이동 유예 · 물속 밖에서 공중으로 5초 넘게 1 stud도 안 내려가면 되돌림(로그 "높이 보정(공중 정체)"). 발 바로 아래 지면이 광선에 보이면 서 있음. 합법 최대 체공(공중 점프 2 + 대시 ≈ 2.0 · 태초 2단 대시) · 태초 장갑 매달림(4 + 0.22초 - 허가가 거절돼도)은 5초 안. 활강은 면제가 아니다(초당 5씩 내려가 스스로 초기화 - 켜 두기 우회 차단). 정체 1회는 리더보드 표시를 안 한다(30초 안 2회째부터).
- **검증 상태**: 공중 정체 검사는 파트 0의 Play 3회를 다 쓴 뒤 넣었다 → **BR1-4a 첫 Play에 S1(가) 정체 항목 · G2a(나) · MV1 · M1-2c를 같이 돌려 확인**(BR1-4a 보고서).
- G2a(나) 항목 기준: 허용 초과 표본부터 ≤ 1.5초(리뷰 4) 또는 허용 아래로 버티면 정체 검사로 ≤ stallSeconds + 1.

## [2] 0-2 공격 속도 · 0-3 상한

**0-2 구현**: `PlayerCombat.getTotalSpeedMultiplier(장비 · 보석, 버프)` - `CombatConfig.attackSpeedCapIncludesBuffs = true`면 (1 + 합) × 버프를 곱한 뒤 ×2.5 하나로 자른다. 기본 **false = 옛 규칙**(버프는 상한 밖 - 실효 최대 ×6.25). 쿨다운(서버 · 클라 예측) · 원거리 발사 시각 · 모션 속도가 같은 함수.

| EconSim(로컬 하네스 · 활 프로필) | 1,000 | 10,000 | 20,000 | 25,300 |
|---|---|---|---|---|
| 기준(옛 코드 · 이번 기본값 둘 다) | 3.7h | 281.9h | 1,275.1h | **1,968.2h** |
| 상위 1% · 스위치 켬 | 4.0h | 385.2h | 1,544.6h | **2,354.2h(+19.6%)** |
| 캐주얼 · 기준 / 켬 | 39.2 / 39.2h | 1,423.9 / 1,659.4h | 6,223.9 / 7,363.0h | 9,568.4 / 11,344.3h |

- 원인: EconSim 세 프로필 전부 **활**(기준 직업) - 신발 속도가 오르면 속사(1 + 치명 15% × 1.5 = ×1.225)가 곧장 상한에 걸린다. 캐주얼 1,000은 그대로(신발 속도가 낮을 때는 안 걸린다).

| 직업 DPS(레벨 100 앵커 · 60초 로테이션 · atk 단위) | 신발 +0% | +50% | +100% | +150%(상한) |
|---|---|---|---|---|
| 대검 | 499.4 | 653.1 | 820.1 | 973.8 |
| 쌍검 | 607.8 | 885.2 | 1,164.3 | 1,441.9 |
| 활(옛 → 켬) | 591.7 | 863.2 | 1,133.7 | **1,406.0 → 1,290.0(−8.3%)** |
| 치유사 딜링(100% 가동) | 385.1 | 576.6 | 768.1 | 960.5 |
| 쌍검 ÷ 대검 | 1.217 | 1.355 | 1.420 | 1.481 |

- 스위치를 켜도 바뀌는 칸은 활 +150%뿐. 활은 여전히 대검의 1.32배(1,290 ÷ 973.8)라 **"모자라서 스킬 계수로 보정"할 상황은 아니다** - 대신 경제 불변(±3%)을 깬다.
- 참고(옛 문제 · 이번 변경과 무관): 신발 속도가 높을수록 쌍검 ÷ 대검이 1.32를 넘는다(+50%부터 1.355). "최저 대비 1.32배"는 앵커(+0%)에서만 지켜진다.
- 다른 스탯 전수: 이동 속도(신발 × 옵션 → ×1.5 · 버프 없음) · 치명 피해(옵션 + 태초 장갑 → +2.2 · 확정 치명 넘침 전환분만 밖 - 설계) · 받는 피해 배율(곱 → 하한 `incomingDamageMultiplierFloor`) · 쿨다운 옵션(축마다 상한) - **버프가 상한 밖에서 곱해지는 것은 공속(속사) 하나**.

**0-3 도달 가능한 최대(8자리 = 장비 3 + 보석 5 전부 태초 · 롤 최대)** - 로컬 계산(`Option.valueOf`):

| 스탯 | 레벨 1,000 | 10,000 | 25,300 | 제안 | 판단 |
|---|---|---|---|---|---|
| 위력 옵션 | +230% | +248% | +255% | +200% | **미적용**(잘린다) |
| 치명 확률(옵션 · + 직업 12 ~ 30%) | +161%p | +173%p | +178%p | 100% | **미적용**(확정 치명 넘침 → 치명 피해 전환이 잘린다) |
| 스킬 피해 옵션(기준값 배) | ×7.7 | ×8.3 | ×8.5 | ×6.5 | **미적용**(잘린다) |
| 최종 피해 버킷 | +105%(강화 +30) | 같음 | 같음 | +105% | **적용**(`CombatConfig.finalDamageBonusCap` - 안 잘림 · EconSim 1,968.2h 그대로) |

- S1 보고서의 추정(위력 +190% · 치명 +133%p · 스킬 ×6.3)은 레벨 계수 · 롤 최대를 덜 넣은 값이었다.

## [3] 0-4 발사 허가 수평 속도

- `HeightGuard.grantAt(… hRate)`: 허가마다 설계 체공 동안의 수평 상한. 보스 발사(`grantLaunch` - 넉백 · 회오리 · 판 털기 · 던지기) = 400/s · 나무 점프대 = (다음 요소까지 평면 거리 + 발판 반경) ÷ 비행 1.1초 × **1.25**(최대 57.3 → 71.6/s) · 수정 부수기 발사 발판 = 클라 포물선의 평면 거리 ÷ 비행 시간(모서리 반경 · 정점 꺾임점 포함) × 1.25 · 통통 열매 · 붙잡기 = 걷기 그대로.
- 리뷰 2: 날아가는 중 새 허가(붙잡기 등)가 앞 허가(보스 400)를 덮어 수평 상한을 끊던 회귀 → 설계 체공 안이면 앞 상한을 이어받는다.
- 검증: M1-2c(나) 나무 발사 **30/30 · 되돌림 0**(허가 54장 · 늦게 온 위치로 확인 23) · 보스 발사 6종 되돌림 0 · S1(가) 발판 허가 표 O.

## [4] 0-5 · 0-6 · 0-7

- **0-5** `/ops stats`(이 서버 메모리) · `/ops stats all`(DataStore `AlphaStats_v1` 키 `summaries` 최근 100 서버 합 - 가동 시간 포함) · 서버 종료(BindToClose) 때 요약 한 줄(끌어오기 0회 서버는 건너뜀 - 리뷰 6) · 검증 모드 = `_verify` 저장소 · Studio = `studio_` 키. `/gg stats`와 같은 문장(`AlphaStats.describe`).
- **0-6** C 둥지 틀(alcove) 파트 19곳 → `Rock` · `Trunk` · `Foliage` · `Water` · `Post` · `Ambient` · 모델 이름 `Outcrop_<해시>` → **`Struct_<구역>_ruinsNNN`**(다른 구조물 규칙에 섞음 - 40곳 겹침 0) · 번개 문 속성(옛 값 = 둥지 id!) · 환경 힌트 속성은 **서버가 시작 때 읽고 지운다**(반딧불 입자 = 서버가 붙임 · 클라 `NestView` 힌트 코드 삭제). 남은 식별 수단 = 구조물 모양 · 통과 덮개(CanCollide false) → A2.
- **0-7** 낙하: 서버가 만든 엘리베이터 발판(물리 · 8/s)으로 발 +57까지 올린 뒤 발판 제거 → 지연 0.25에서 **서버 궤적 55**(실제 57 · −3.5%) · 되돌림 0 · 판정 = `excluded:tree`(스폰이 허브 나무 구역 - 낙하 제외 규칙). 구역 밖 실제 피해 적용은 미확인. 봉투: 개발 계정 `gg_tainted` 검사를 그 항목 동안만 끄고 실제 `eligibility` → `velocity_hold` · 합법 시간 → `ok`.

## 검증

| 실행 | 블록 | 결과 |
|---|---|---|
| Play 1(계측) | G2a(나) | 4/6 - 흔적으로 원인 좁힘 |
| Play 2 | S1(가) 12/12 · (나) 11/11 · MV1(가) 23/23 · (나) 14/14 · M1-2c(가) 16/16 · (나) 10/11 · D1-2(나) 6/6 · M1-3T(나) 18/19 · G2a(나) 4/6 | M1-2c(나) X = 검증이 `reset` 없이 서버 이동(S1 수평 규칙 뒤 옛 검증) → 고침 |
| 같은 Play(수동) | 지연 0.25 엘리베이터 낙하 · 정체 재현 | 위 [4] |
| Play 3(리뷰 반영 뒤) | S1(가) 12/13 · (나) **11/11** · MV1 23/23 · 14/14 · M1-2c(가) 16/16 · (나) **11/11** · M1-3T(나) 18/19 · G2a(나) 4/6 | X: 지연 합성 시험 조건(버킷 0 시작 - 검증 쪽) · M1-3T 캡슐 = 번개 문 속성을 지운 영향(검증 쪽) · G2a = 위 [1] |
| Play 3 뒤 코드 | 공중 정체 검사 · 캡슐 검사에 서버 문 목록 · 지연 시험 조건 | **Play 미실행 - BR1-4a 첫 Play에서 확인** |

- 동반 실행한 옛 블록과 이유: M1-2c(가)(나)(발사 허가 수평 상한) · MV1(가)(나)(붙잡기 허가 · grantAt) · M1-3T(나)(번개 문 · 둥지 이름) · D1-2(나)(공격 간격 함수). 생략: W1(원거리 발사 시각 - 기본값 경로 동일) · S13(앵커 DPS - 기본값 동일).
- EconSim: 기본값 1,968.2h(옛 코드와 같음) · 스위치 켬 2,354.2h.

## 리뷰(서브에이전트)

| # | 지적 | 반영 |
|---|---|---|
| 1 | C 둥지 모델 이름 · 새 속성이 C 전용 = 여전히 표식 | O - 모델 이름 = 구조물 규칙 · 속성은 서버가 읽고 지움 · 반딧불 = 서버 |
| 2 | 붙잡기 허가가 보스 발사 수평 상한(400)을 덮어씀 | O - 설계 체공 안이면 이어받기 |
| 3 | EconSim 캐시 키에 새 스위치 없음 | O(보고 수치는 케이스마다 새 프로세스라 영향 없음) |
| 4 | G2a 기준 ≤ 6초로 느슨 · 흔적 누수 | O - 허용 초과 표본부터 ≤ 1.5 · 절 끝에 흔적 끄기 |
| 5 | 지연 합성 시험이 허가 없이도 통과 | O - 2초 비행 · 허가 없음 대조군 |
| 6 | 한 키에 동시 종료 몰림 · 빈 요약 | 일부 - 빈 요약 건너뜀(키 나누기는 알파 규모에서 보류) |
| 7 | 코스 발판 모서리 · 정점 꺾임점 | O |
| 참고 | 최종 피해 상한 1.05를 강화 데이터와 따로 박음 | 유지(강화 상한이 오르면 이 값도 - 주석) |
| 2차-1 | 루트 고정(잡힘 · 끼임)이 풀린 첫 폴링에 바로 정체 되돌림 | O - skip에서 초기화 |
| 2차-2 | 붙잡기 매달림 4초(허가 거절 시) > 3.5초 | O - 상한 5초 |
| 2차-3 | 허가 "내려가기만" 20초 면제 우회 | O - 설계 체공 안만 |
| 2차-4 | 활강 켜 두기 = 무한 면제 | O - 활강 면제 삭제 |
| 2차-5 | 물 위(헤엄 상태 안 보임) · 도착 대기 | O - 물속 초기화 · 도착 대기는 5초 안 |
| 2차 공통 | 오탐 한 번에 리더보드 기록 거절 | O - 정체 1회는 표시 안 함 |

## 결정 필요

| # | 내용 | 추천 |
|---|---|---|
| 1 | 공속 상한에 속사 버프 포함(스위치 켜기) = 상위 1% +19.6% | **켜지 않음(현행 유지)** - 켜려면 EconSim 목표(2,190h ± 10%) 안으로 들어오는 보정(예: 속사 최대 배율 ↓ 대신 활 평타 계수 ↑)을 같이 정해야 한다 |
| 2 | 상한 없는 3종(위력 · 치명 확률 · 스킬 피해 옵션) 제안값이 도달 최대보다 낮음 | 상한을 도달 최대 위(위력 +260% · 스킬 ×8.6)로 올려 "안 잘리는 천장"만 두기 · 치명 확률은 100% 상한 + 넘침 전환 유지 |
| 3 | 신발 속도 구간의 쌍검 ÷ 대검 1.36 ~ 1.48(앵커만 1.32 이내) | 알파 전 직업 밸런스 단계에서 재측정 |
| 4 | 공중 정체 5초 | BR1-4a 첫 Play 확인 뒤 유지 · 알파 로그로 조정 |
| 5 | C 둥지 남은 식별 수단(모양 · 통과 덮개) | A2 |
