# S1 보고 - 이동 보안 + 획득 보안 + 경제 상한 점검 (2026-09-27 · 밤샘 묶음)

지시 = "[밤샘 묶음] 파트 S1". 원칙 = 클라가 보낸 값은 서버가 직접 본 사실과 맞을 때만 · 지연 0.25에서는 "지금 발" 대신 "마지막 지면" · 자동 제재 없음(되돌림 · 격리 · 보류 · 검토 대기 · 로그). 검증 = COMMON §7-1. **SAVE_VERSION 44**(audit) · **place 저장 불필요**.

**한 줄 요약**
- 이동: 서버 **수평 이동 토큰 버킷**(합법 이동 목록 = 데이터 한 곳) · 표시 없는 순간이동 = 되돌림(옛 "50 넘으면 순간이동 인정" 삭제) · 높이 허용 = **해금 단계별**(환생 0 = 8.92 - 미해금 공중 점프 적발) · 낙하 = **서버 궤적**(클라 신고 없어도 서버가 처리) · **비밀 둥지 C = 서버 전용**(클라 0곳 · 가까이 가야 앵커).
- 획득: 스테이지 **하드 상한 25,300**(쓰기 거절 · 저장 · 불러오기 때 상한으로 자름) · 배정밀도 여유 **약 8,600스테이지** · 태초 **발급 원장**(굴림 id · 출처 · 확률 · 스테이지 · 시각 · JobId · 번호) · 원장 없는 태초 = 격리 · 집계 = 드랍 출처만 · **속도 봉투**(25,300 = 1,169시간) · **포아송 검사** · 처치 속도 · **운영 명령 6종**.
- 검증: S1(가) **11/11** · (나) **9/9**(Play 3 - 리뷰 반영 뒤) · 지연 0.25 실측 걷기 18초 · 대시 8회 · 서버 순간이동 3회 **되돌림 0** · 속도 조작 적발 · 옛 블록 MV1 · M1-3T · M1 · D1 · W1 O · **G2a(나) 4/6 = 미확인**(아래 검증).
- **W1 밸런스 회귀 발견 · 되돌림**(원거리 발사 시각 - `8075112`).

---

## [1] 이동 보안

### 1-1 수평 속도 검사(`HeightGuard.evaluateHorizontal` · TerrainServer 0.25초 폴링)

| 항목 | 값(`MovementConfig.moveGuard`) |
|---|---|
| 방식 | 토큰 버킷: 초당 rate만큼 차고(최대 rate × 1.5초 + 3) 표본 사이 수평 이동만큼 쓴다 · 모자라면 **마지막 정상 자리로 되돌림**(킥 · 제재 없음 · 위반 누적 로그 - 5초에 한 줄) |
| rate(합법 최대 중 켜진 것) | 걷기 상한 24 × 물리 여유 1.1 · 활강(서버 Attribute `Gliding`) 30 × 1.1 · 물 = 걷기 + 물살 18 · 발사 허가 비행 400/s |
| 따로 쌓는 허가 | 대시 = 서버 `DashServer`가 준 거리 × 1.15(1.3초 안 - 2단 대시 = 두 번) · 선인장 밀림 26(1초) |
| 검사 안 함 | 붙잡힘 · 가둠 · 석상(exempt) · 루트 고정 · 사망 |
| 서버 순간이동 뒤 유예(1초) | **도착 자리 근처만** 새 기준(리뷰 3 - 유예가 "자유 이동 창"이 아니다) · 지연으로 옛 자리 표본이 끼면 도착 자리로 되돌림(위반으로 세지 않음) |
| 발사 허가 속도 400/s | **설계 체공(`permit.expiresAt`) 안만**(리뷰 4 - 착지 유예 · 미사용 창에서는 걷기 · 활강 속도) |
| 합법 목록(데이터 `legal`) | 걷기 · 대시(공중 · 2단) · 활강 · 물살 · 발사 허가(점프대 · 통통 열매 · 보스 던지기 · 회오리 · 판 털기 · 넉백 · 붙잡기 올라서기) · 선인장 · 원거리 공중 정지 · 일어나기(이동 0) · 사다리 · 덩굴(수직) · 서버 순간이동(Travel · 리프트 · 복귀 · 보스 입장 · 보스 기믹) |

- **서버가 캐릭터를 옮기는 곳 감사**(12곳): 전부 `HeightGuard.reset` 또는 `exempt`를 부르게 맞췄다 - 새로 넣은 곳 = 보스 무덤 끌기(`BossGimmicks`) · 재생 밀어내기(`BossPatterns`). 나머지는 이미 있음.

### 1-2 순간이동

- 옛 규칙: 한 폴링에 50 넘게 움직이면 "순간이동"으로 **기준을 새로 잡았다**(= 50씩 끊어 가면 통과). **삭제** → 서버 순간이동은 `reset` 표시로만 기준을 새로 잡고, 표시 없는 큰 이동은 수평 검사가 되돌린다(위로 큰 이동은 높이 검사).
- 실측: 서버 표시 없이 옮긴 50 → `hrevert`(돌아간 거리 0.0) · `/gg` 없이 `execute_luau` 사본 Travel로 옮긴 160 → 되돌림(표시가 진짜 모듈에 안 갔다 = 정상 적발).

### 1-3 환생 해금 서버 검증(재확인)

- 공중 공격 예산 · 공중 3타 강공격 · 공중 대시 = 서버 거부(MV1(나) 14/14 이번에도 O) · 활강 = 서버 `GlideState`가 해금 단계 확인.
- **새로 막음 - 미해금 공중 점프**: 공중 점프는 요청이 아니라 클라 물리라 서버가 몰랐다(높이 허용 22.38 = 공중 점프 2회 고정). → 허용치 = **해금된 공중 점프 수 기준**(환생 0 = 8.92 · 1 = 15.65 · 3+ = 22.38 - `MoveTier`). 실측: 환생 0이 발 12 → strike · revert.

### 1-4 낙하 = 서버 궤적

- 서버 `AirState`가 체공마다 **루트 최고점**과 착지 높이를 기록 → 피해 속도 = √(2g × (최고점 − 착지)). 최고점을 새로 잡는 때 = 떨어지던 가장 낮은 곳에서 **2 stud 넘게 다시 오름**(공중 점프 · 발사) · 활강(서버 `Gliding`이고 실제 하강 ≤ 8/s)뿐(리뷰 5 - 0.06 올리기 · 착지 직전 Gliding 켜기로 최고점을 못 지운다). 클라 신고 속도는 대조 로그만(`FallServer.mismatches`).
- **서버가 아직 착지를 못 봤을 때 온 클라 신고 = `pending`**(대조용으로 적기만) → 서버 착지(0.05초 뒤) 때 서버 궤적으로 처리(리뷰 5 - 정점 근처에서 일찍 신고해 낮은 속도로 끝내는 길 차단). 물 = 서버 복셀 판정 · 사다리 = 서버 체공 세션 표시만(클라 표시 안 믿음) · 활강 켜기 = 서버가 공중으로 볼 때만(리뷰 9).
- 심연 복귀(`TerrainServer`)도 체공 세션을 끝낸다(리뷰 6 - 옛 절벽 최고점이 남지 않게).
- 실측: 클라 신고 2000 · 서버 높이 3 → 쓴 속도 34.3(서버) · 결과 none. 궤적 없는 합성 세션(옛 검증)만 클라 값을 쓴다.

### 1-5 비밀 둥지 서버 전용

- C 40곳 명세 = `server/SecretNestData`(ServerScriptService - 클라 복제 없음). 공유 `NestData`는 **서버 실행 중 · Studio edit(굽기)에서만** 합친다 → 서버 코드는 전과 같은 전체 목록(93) · 클라는 53(A · B).
- C 모델 이름 = 중립(`Outcrop_<해시>` - 옛 `Nest_t1_c_h1`) · 앵커(알 자리 + 둥지 고리 + 프롬프트) = 서버 창고 → **누군가 45 stud 안에 오면 월드에 꺼내고 60 밖이면 다시 넣는다**.
- 실측(클라): C 명세 0 · 월드 C 앵커 0 · `_c_` 모델 0 · `SecretNestData` 접근 불가 → 둥지 옆으로 가면 그 앵커 하나(프롬프트 포함)만 나타남. 원격 줍기 → `far` 거절.
- 지형 서명 7구역 전부 그대로(C 순서가 바뀌어도 마스크 결과 같음 - Edit 대조).
- 남는 단서(결정 4): 둥지 구조물 모양(가짜 벽 · 덩굴 덮개 파트 이름) · 환경 힌트 파트(`NestHint` - 설계상 보이는 단서) · 번개 문 `TimedDoor`.

### 지연 0.25 실측(수동 Play - 클라가 직접 움직임)

| 동작 | 결과 |
|---|---|
| 걷기 24/s 18초(왕복) | 되돌림 **0** |
| 실제 대시 요청 8회(서버 허가 → 클라 트윈) + 걷기 | 되돌림 **0**(첫 측정 1건 = 허용 6.7에 6.8 경계 → 걷기 여유 1.1 · 버킷 1.5초로 넓힘) |
| 속도 조작 40/s 6초 | 되돌림 1 · 전진 179(합법 최대 약 201 안으로 눌림) |
| 50씩 순간이동 | 되돌림(표본마다) |
| 활강 · 물살 · 발사 허가 비행 | 순수 판정만(실제 키 입력 활강 · 보스 판 털기 지연 실측 = **미확인**) |

## [2] 획득 보안(태초)

### 2-1 하드 상한 = 25,300

- 옛: `safeStageCap` 34,230(배정밀도 안전 · 일반 이동만) · 25,300은 설계 값뿐 → **`InfiniteStageConfig.hardMaxStage = 25,300`**: 스테이지 이동(`hard_cap`) · 보스 잔류 다음 칸 · `setInfiniteStage` · `raiseInfiniteBest` · `setBossCleared` 거절 + 로그 · **저장 직전 · 불러온 뒤(migrate 끝) 넘는 값 = 상한으로 자름**(리뷰 7 - 옛 "저장 거부"는 골드 · 아이템까지 못 쓰게 했다) + 경고 로그. 실측 25,301 → 쓰기 false · 저장 전 25,300으로 자름.

### 2-2 배정밀도 여유

| 최악 조합(보스 HP) | 1e300 안 최대 스테이지 | 25,300에서 |
|---|---|---|
| 4인 · tier1 · 토벌 없음 | 34,437 | 2.6e221 |
| 12인 · tier6 r² · 토벌 ×10(가정) | 34,165 | 5.7e223 |
| 12인 · tier6 r² · 토벌 ×1,000(가정) | **33,932** | 5.7e225 |

- 보스 HP = 80 × 1.02^(s−1) × 24(최대 배율 수호자) × N^0.93 × tier r² × 토벌 배율(아직 없음 - 가정). 게임 전체 한계는 레벨 경험치 누적(`safeStageCap` 34,230)이 먼저다. → **상한 확장 여유 ≈ 8,600스테이지**(33,932 − 25,300).

### 2-3 발급 원장

- 태초가 굴려진 순간(`CombatResolution`): 굴림 id(GUID) · 그 굴림의 태초 확률(잡몹 = 레벨 감쇠 뒤 확률 · 보스 첫 클리어 0.01% · 토벌 0.002% · 반짝이) → 번호 발급 뒤 원장 저장소(`PrimordialLedger_v1` 키 `roll_<id>`)에 { rollId · userId · 출처 · 확률 · 스테이지 · 시각 · JobId · 세계 번호 · 부위 } 한 번 쓰기(재시도 3) · 아이템 각인에 `rollId` · `p` · `ledger`.
- **원장 없는 태초 = 격리**(로드 때 `AcquisitionAudit.auditProfile` - rollId 없음 · 원장 키 없음 · 다른 userId): 각인 `quarantined` · 번호 = 결번(명예의 전당 · 집계 제외 목록) · 칭호 "태초의 선택" 조건 다시(남은 집계 대상 태초가 없으면 회수) · **아이템은 그대로**(운영 판단).
- **원장 제도 이전 태초(D1 ~ S1 사이 번호 발급)** = v44 이관 때 `preLedger` 표시 → 격리 안 함 · 집계 대상(리뷰 1 - 첫 초안은 전부 격리였다).
- 원장 쓰기 실패 · 미완(각인에 `p`가 남음) = 격리 대신 **로드 때 다시 쓴다**(리뷰 2) · 운영 해제(`releasedByOps`)는 다시 검사하지 않는다 · 해제 때 결번 목록에서도 뺀다(`includeNumber`).

### 2-4 집계 규칙

- 태초 리더보드 · 세계 번호 집계 · "태초의 선택" = **드랍 출처만**(`countableSources` = 보스 첫 클리어 · 토벌 · 반짝이 · 잡몹). 제외 = 출처 태그 없는 것(분해 보석 · 환생 무기 · 펫 합성) · 운영 지급(kind "ops") · 선물 · 격리 · 회수 · 옛 태초.
- 동점 = 먼저 달성(값 = 개수 × 1e10 + (9999999999 − 달성 시각)). 회수 번호 = 결번(번호 카운터는 되돌리지 않는다 · 제외 목록 `PrimordialExcluded_v1`).
- **태초 리더보드 자체는 아직 없다**(값 인코딩 · 집계 함수만 - UI · 순위표는 결정 3).

### 2-5 속도 봉투(EconSim 프로필 `envelope`)

- 전 부위 태초(스테이지 1부터) · 최적 파티(4인 같이 사냥) · 조작 효율 1 · 최소 오버헤드 → 로컬 EconSim 곡선(`AuditConfig.envelope.curve`) × **1.1**을 넘는 계정 최고 스테이지 = 리더보드 등재 보류(`Leaderboard.eligibility` "velocity_hold") + 검토 대기. x축 = 계정 플레이 시간(`profile.audit.playSeconds` - 1분마다).

| 이정표 | 봉투(합법 최대) | 참고: 상위 1%(목표 모형) |
|---|---|---|
| 1,000 | 1.7시간 | 3.7시간 |
| 10,000 | 201시간 | 282시간 |
| 20,000 | 771시간 | 1,275시간 |
| **25,300(천장)** | **1,169시간 = 하루 24시간 48.7일 · 12시간 97.4일** | 1,968시간 |

- v44 이관: 옛 계정 플레이 시간 = 그 계정 최고 스테이지에 합법으로 닿는 최소 시간(봉투 역함수 - 옛 진도를 보류하지 않게).

### 2-6 확률 검사

- λ = 계정이 실제로 굴린 태초 확률 합(드랍 굴림마다 `p × 개수` - `profile.audit.lambda`). P(X ≥ 집계 대상 보유 수 | λ) < **1e-6** = 검토 대기(자동 제재 없음). 실측: 운 좋은 계정(λ 0.05 · 1개 · P 0.05) = 통과 · 태초 3개 · λ 0.001(P 1.7e-10) = 검토.

### 2-7 처치 · 보스 클리어 속도

- 60초에 처치 > 240 · 1시간에 보스 클리어 > 120 = 로그 + 검토 대기(10분에 한 번).

### 2-8 운영 명령(`/ops` - `OpsConfig.userIds`만 · 서버 검증 · 기록 `OpsLog_v1`)

| 명령 | 동작 |
|---|---|
| `release <userId> <번호\|rollId>` | 격리 해제(그 사람이 이 서버에 있을 때 · 결번 목록에서 뺌 · 바로 저장) |
| `revoke <userId> <번호\|rollId>` | 회수(아이템 남김 · 결번 · 칭호 다시 = 자동 격리와 같은 함수 `titleStillEarned` · 바로 저장) |
| `lbremove <personal\|class_<직업>> <userId>` | 리더보드 항목 제거 |
| `versions <userId>` · `restore <userId> <version>` | DataStore 저장 버전 목록 · 복구(**30일 보관 → 탐지 · 복구는 30일 안**) · 그 사람이 이 서버에 없을 때만 |
| `review <userId>` | 이 서버 검토 대기 기록 |

- 실측: release(위조 번호) → released · revoke → revoked · 기록 남음.

### 검증 표(지시)

| 항목 | 결과 |
|---|---|
| 원장 없는 태초 주입 → 격리 | O(위조 no_roll_id 격리 · 원장 있는 것은 유지 · 칭호 조건 다시) |
| 봉투 초과 → 보류 | 순수 판정 O · 실제 자격 판정은 **미확인**(개발 계정이 `/gg` 표시로 자격이 먼저 막힌다 - `gg_tainted`) |
| 운 좋은 가짜 계정(봉투 안 · p > 1e-6) → 통과 | O |
| 분해 보석 · 환생 무기 미집계 | O(출처 태그 없음 = 집계 0) |
| 25,301 저장 → 25,300으로 자름 | O(리뷰 7 반영 뒤 Play 3) |

## [3] 경제 상한 전수(조사 - 적용은 결정 대기)

| 스탯 | 상한 | 출처 · 최대 추정 | 제안 |
|---|---|---|---|
| 공격 속도 | ×2.5 | 신발 + 신속 옵션 · **활 속사 버프(quickShot ×2.5)는 상한 밖에서 곱해져 실효 최대 ×6.25** | 버프도 전체 ×2.5 안으로(결정 5) |
| 치명 확률 | 없음 | 옵션 최대 +133%p | 100% 명시 |
| 치명 피해 | +2.2 | 옵션 +1.33 + 태초 장갑 +0.4(확정 치명 넘침 +0.4는 상한 밖) | 유지 |
| 이동 속도 | ×1.5 | 신발 · 옵션 | 유지 |
| 점프력 | +10% | 출처 없음(펫 예정) | 유지 |
| 쿨다운 감소 | 공용 없음 · 옵션별 50 · 50 · 90% | 직업 옵션 | 유지 |
| 흡혈 | % 없음 · 초당 최대 체력 4%(버킷) | 옵션 최대 약 19% | 표시 20% |
| 방어 | 옵션 32% · 최종 감소 < 1 | 옵션 최대 약 107% → 상한에 걸림 | 유지 |
| 최대 체력 | 옵션 20% | 갑옷 절대값 | 유지 |
| 경험치 | 옵션 25% | × 파티 ×1.2 × 환생 ×1 ~ 6 | 유지 |
| 골드 · 드랍 | 출처 없음 | - | 생기면 25% |
| 피해(위력 옵션) | **없음** | 옵션 최대 +190% + 태초 장갑 기본 | +200% |
| 최종 피해 버킷 | **없음** | 강화 +105%(maxLevel 30이 사실상 상한) | +105% |
| 직업 스킬 피해 옵션 | **없음** | 대검 Q 최대 약 +567% | 기준값 × 6.5 |

- **합연산 버킷 +21.9%** = 환생 뒤 레벨 마일스톤(상한 1.02^10 − 1 · `MilestoneData` · 레벨 약 8,650에서 닿음 - 공격력 ×(1 + 버킷)). **버킷 밖 곱연산 장기 보상**: 강화 곱 몫(+30 = ×9.76) · 강화 최종 피해 +105% · 환생 무기 등급 1.45^n · 캐릭터 레벨 무기 배율 · 환생 경험치 ×1 ~ 6 · 파티 경험치. 칭호 · 둥지 도감 · 보스 도감 = 전투력 없음.

## [4] 조사

| 항목 | 직업별 / 계정 공통 |
|---|---|
| 무한 스테이지(지금 · 최고) · 최고 보스 클리어 · 보스 첫 클리어 기록 | **직업별**(계정 최고 = 파생 `getAccountBestStage` · 방지권 지급 기록만 계정) |
| 캐릭터 레벨 · 환생 횟수 · 착용 장비 3부위 · 무기 강화 · 보석 · 마일스톤 도달 레벨 | **직업별**(가방 · peakLevel · 보석 가루 · 마일스톤 해금 개수는 계정) |
| 골드 · 재료 · 칭호 · 둥지 · 알 · 이동 단계(MoveTier - 최대 환생 파생) · 획득 감사(v44) | **계정** |

- **C1 끌어오기 계측(`/gg stats` · AlphaStats)은 라이브 알파에서 못 쓴다**: 수집(`MonsterState.notePull`)은 라이브에서도 돌지만 읽는 곳이 DevTools(Studio 전용 가드)뿐이고 서버 메모리라 서버가 닫히면 사라진다 → 결정 6(추천: `/ops stats` 추가 + BindToClose 때 DataStore 요약).

## 검증

| 실행 | 블록 | 결과 |
|---|---|---|
| 로컬 하네스 · EconSim | 배정밀도 · 봉투 · 상위 1% 대조 | 봉투 1,169h · 상위 1% 1,968.2h(W1 회귀 발견 → 되돌림) |
| Edit | 7구역 지형 서명 · C 합침 93 | 전부 일치 |
| Play 1(자동) | S1(가) 10/10 · (나) 8/9 · W1(가) 9/9 · (나) 3/3 · MV1(가) 23/23 · (나) 14/14 · G2a(가) 5/5 · M1-3T(가) 30/30 · M1(가) 26/26 · D1(가) 29/29 | X 1 = 낙하 기대값 계산 실수(√(2g·3) = 34.3이 맞음) → 검증 고침 |
| 같은 Play(수동) | 클라 비밀 둥지 0 · 근접 노출 | O |
| 지연 0.25(수동) | 걷기 · 대시 · 속도 조작 · 순간이동 | 경계 오탐 1 → 여유 조정 → 다시 0 |
| Play 2(자동) | S1(가) **10/10** · (나) **9/9** · W1(가) 9/9 | O |
| Play 3(자동 - 리뷰 반영 뒤) | S1(가) **11/11**(유예 · 허가 창 항목 추가) · (나) **9/9** · MV1(가) 23/23 · (나) 14/14 · W1(나) 3/3 · G2a(가) 5/5 · **G2a(나) 4/6** | X 2 = 아래 |
| 같은 Play(수동 · 지연 0.25) | 심연 복귀(서버 순간이동) 3회 | 도착 자리 유지 · 수평 되돌림 **0** |

- **G2a(나) X 2(띄워 두기 되돌림 없음 → 리더보드 거절 항목도 연쇄 X) = 미확인**: 같은 Play에서 같은 동작(점프 → 넉백 → 허용 + 3에 붙잡기)을 서버 `execute_luau`로 그대로 하면 **0.95초에 되돌림**(진짜 폴링 · 진짜 모듈). 체인 첫 블록(Play 시작 5초 뒤)에서만 안 잡혔다. 원인 확정 못 함 → 다음 Play 때 볼 계측 추가(서버가 본 띄워 두기 최고 높이 · 허용 · `debugOff`를 결과 줄에 찍는다). Play 3회 상한이라 재실행 안 함. 코드 결함이면 "높이 부정이 체인 첫머리에서 안 잡힘"이므로 **다음 세션 첫 Play에서 G2a(나)부터 본다**.
- 부수 수정: S1(나) 검증 태초에 `itemLevel` 누락 → 보석 공방 패널 `CharacterLevel:164` 오류(검증 데이터 결함 - 넣음) · 높이 보정 로그가 해금 단계 허용치 대신 최대치를 찍던 것.
- 낙하 지연 0.25 실측(실제 높은 곳에서 뛰어내리기) = **미확인**(순수 · 서버 경로 검증만 - MV1(나) · S1(나)).

- 자동 검증 Play **3회**(상한 3). 옛 블록을 돌린 이유: MV1(낙하 · 체공 · 대시 허가) · G2a(순간이동 기대값 변경 - "reset" → "revert") · M1-3T · M1(둥지 데이터 이동) · D1(저장 이관 v44) · W1(원거리 되돌림 + 리뷰 반영).
- **옛 기대값 변경**: G2a(가) "표시 없는 순간이동" = `reset,ok,reset,ok,ok` → `reset,ok,strike,revert,strike`(S1 규칙) · D1(가) 이관 결과 버전 = 43 → ≥ 43.

## 리뷰(서브에이전트)

| # | 지적 | 반영 |
|---|---|---|
| 1 | 원장 제도 이전 정상 태초가 로드 때 전부 격리(칭호 회수까지) | O - v44 `preLedger` 표시 · 집계 대상 |
| 2 | 원장 쓰기 실패 · 미완 태초가 격리 · 운영 해제 뒤 다음 로드에 다시 격리 · 결번이 안 풀림 | O - 로드 때 원장 다시 쓰기 · `releasedByOps` 건너뜀 · `includeNumber` |
| 3 | 서버 순간이동 뒤 유예 1초 = 수평 검사 없는 자유 이동 창 | O - 도착 자리 근처만 받기(`hAnchor`) · 검증 추가 |
| 4 | 발사 허가 속도 400/s가 허가가 살아 있는 동안(착지 유예 포함 최대 약 4초) 계속 | O - `permit.expiresAt` 안만 · 검증 추가 |
| 5 | 낙하: 이른 클라 신고가 정점 근처 낮은 속도로 끝냄 · 물 · 사다리 클라 표시 신뢰 · 작은 오르기 · 활강 켜기로 최고점 지우기 | O - `pending` → 서버 착지로 처리 · 서버 판정만 · 2 stud 규칙 · 활강 하강 ≤ 8/s |
| 6 | 심연 복귀가 체공 세션을 안 끝냄 | O - `AirState.reset` |
| 7 | 스테이지 상한 초과 = 저장 전체 거부(골드 · 아이템도 잃음) | O - 상한으로 자름 · 불러올 때도 |
| 8 | 비밀 둥지 단서(구조물 파트 이름 · `NestHint` · `TimedDoor` 속성) | 결정 4(A2 아트 교체 때 - 파트 이름 · 속성 중립화) |
| 9 | 땅에서 활강 켜기로 수평 상한 올리기 · 운영 회수 칭호 규칙이 자동 격리와 다름 · 운영 명령 뒤 저장 지연 | O - 서버 공중 확인 · `titleStillEarned` · `ImmediateSave` |
| 참고 | `restore`는 다른 서버 세션 잠금을 모른다 · 로드마다 원장 `GetAsync` | 운영 절차 주석(대상이 오프라인인지 확인) · 알파 규모에서 유지 |

## 결정할 것

| # | 내용 | 추천 |
|---|---|---|
| 1 | 수평 검사 여유: 걷기 × 1.1 · 버킷 1.5초 → **10% 미만 속도 조작은 못 잡는다**(누적 거리로는 합법 최대 안) | 유지(오탐 0 우선) · 알파 로그(`hViolations`)로 조정 |
| 2 | 원장 이전 태초 = `preLedger`로 집계 대상(위조 여부는 원장이 없어 못 가림) | 유지(알파 전 발급분은 개발 계정뿐) |
| 3 | 태초 리더보드 UI · 순위표 없음(값 · 집계만) | U1 · BR2 |
| 4 | 비밀 둥지 남은 단서(구조물 모양 · 덮개 파트 이름 · 힌트 파트) | A2 아트 교체 때 파트 이름 중립화 |
| 5 | 활 속사 버프가 공격 속도 상한 밖(실효 ×6.25) | 버프 포함 전체 ×2.5(밸런스 재측정 필요) |
| 6 | C1 끌어오기 계측 라이브 불가 | `/ops stats` + 종료 때 요약 저장 |
| 7 | 발사 허가 비행 수평 400/s(판 털기 350) - 설계 체공 안에서는 점프대도 400까지 통과 | 보스 발사만 400 · 점프대는 설계 수평 속도 × 여유로 좁히기(BR1-4) |
| 10 | G2a(나) 띄워 두기 체인 첫머리 미적발(미확인) | 다음 세션 첫 Play에서 계측 줄 확인 · 코드 결함이면 S1 후속으로 |
| 8 | 경제 상한 없는 스탯 4종(치명 확률 · 위력 · 최종 피해 · 스킬 피해 옵션) 제안값 | [3] 표 제안값 적용 |
| 9 | 봉투 x축 = 계정 플레이 시간(자리 비움도 센다) | 유지(보수적 - 자리 비움은 봉투를 넓히는 쪽) |
