-- 자동 생성(roblox/tools/blender/meta_to_luau.py) - 손으로 고치지 말 것. 원본 = roblox/art/weapons/bow.meta.json
return {
	rigId = "bow", version = "A2-N2", pivot = "Grip",
	attachments = { Grip = { 0, 0, 0 }, Tip = { 2.87, 0, 1.4 }, StringNock = { 0, 0, 1.4 } },
	looks = {
		normal = { totalTris = 432, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
		} },
		legendary = { totalTris = 668, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Tips"] = { color = "#FF9933", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Fuller"] = { color = "#FF9933", neon = false },
		} },
		transcendent = { totalTris = 782, parts = {
			["Riser"] = { color = "#262230", neon = false },
			["Grip"] = { color = "#181620", neon = false },
			["Limb_Top"] = { color = "#262230", neon = false },
			["Limb_Bottom"] = { color = "#262230", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Tips"] = { color = "#D6B03E", neon = false },
			["Gem"] = { color = "#FFD65A", neon = true },
			["Fuller"] = { color = "#D6B03E", neon = false },
			["Runes"] = { color = "#D6B03E", neon = false },
			["Wing_R"] = { color = "#262230", neon = false },
			["Wing_L"] = { color = "#262230", neon = false },
			["Shards"] = { color = "#262230", neon = false },
			["Crack1"] = { color = "#FFD05C", neon = true },
			["Crack2"] = { color = "#FFD05C", neon = true },
		} },
		rare = { totalTris = 568, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Fuller"] = { color = "#4DA6FF", neon = false },
		} },
		epic = { totalTris = 624, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Fuller"] = { color = "#A64DFF", neon = false },
		} },
		relic = { totalTris = 624, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Tips"] = { color = "#FFD700", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Fuller"] = { color = "#FFD700", neon = false },
			["Runes"] = { color = "#FFD700", neon = true },
		} },
		ancient = { totalTris = 708, parts = {
			["Riser"] = { color = "#684228", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Limb_Top"] = { color = "#684228", neon = false },
			["Limb_Bottom"] = { color = "#684228", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Tips"] = { color = "#E0393E", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Fuller"] = { color = "#E0393E", neon = false },
			["Runes"] = { color = "#E0393E", neon = false },
			["Wing_R"] = { color = "#E0393E", neon = false },
			["Wing_L"] = { color = "#E0393E", neon = false },
		} },
		primordial = { totalTris = 783, parts = {
			["Riser"] = { color = "#ECE2F0", neon = false },
			["Grip"] = { color = "#784682", neon = false },
			["Limb_Top"] = { color = "#ECE2F0", neon = false },
			["Limb_Bottom"] = { color = "#ECE2F0", neon = false },
			["String"] = { color = "#EBEBEB", neon = false },
			["Tips"] = { color = "#ECE8F6", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Fuller"] = { color = "#FF3CC8", neon = false },
			["Runes"] = { color = "#ECE8F6", neon = false },
			["Wing_R"] = { color = "#FF3CC8", neon = false },
			["Wing_L"] = { color = "#FF3CC8", neon = false },
			["Crystals"] = { color = "#FF3CC8", neon = true },
			["Halo"] = { color = "#FF3CC8", neon = true },
		} },
	},
}
