-- 자동 생성(roblox/tools/blender/meta_to_luau.py) - 손으로 고치지 말 것. 원본 = roblox/art/weapons/dualblade.meta.json
return {
	rigId = "dualblade", version = "A2-N2", pivot = "Grip",
	attachments = { Grip = { 0, 0, 0 }, Tip = { 0, 0, 2.1 } },
	looks = {
		normal = { totalTris = 406, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#706862", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Pommel"] = { color = "#706862", neon = false },
		} },
		legendary = { totalTris = 608, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#FF9933", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Pommel"] = { color = "#FF9933", neon = false },
			["Fuller"] = { color = "#FF9933", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
		} },
		transcendent = { totalTris = 694, parts = {
			["Blade"] = { color = "#262230", neon = false },
			["Guard"] = { color = "#D6B03E", neon = false },
			["Grip"] = { color = "#181620", neon = false },
			["Pommel"] = { color = "#D6B03E", neon = false },
			["Fuller"] = { color = "#D6B03E", neon = false },
			["Gem"] = { color = "#FFD65A", neon = true },
			["Runes"] = { color = "#D6B03E", neon = false },
			["Wing_R"] = { color = "#262230", neon = false },
			["Wing_L"] = { color = "#262230", neon = false },
			["Shards"] = { color = "#262230", neon = false },
			["Crack1"] = { color = "#FFD05C", neon = true },
		} },
		rare = { totalTris = 516, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#706862", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Pommel"] = { color = "#706862", neon = false },
			["Fuller"] = { color = "#4DA6FF", neon = false },
		} },
		epic = { totalTris = 586, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#A64DFF", neon = false },
			["Grip"] = { color = "#603E28", neon = false },
			["Pommel"] = { color = "#A64DFF", neon = false },
			["Fuller"] = { color = "#A64DFF", neon = false },
		} },
		relic = { totalTris = 556, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#FFD700", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Pommel"] = { color = "#FFD700", neon = false },
			["Fuller"] = { color = "#FFD700", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Runes"] = { color = "#FFD700", neon = true },
		} },
		ancient = { totalTris = 640, parts = {
			["Blade"] = { color = "#CED4E0", neon = false },
			["Guard"] = { color = "#E0393E", neon = false },
			["Grip"] = { color = "#5A301E", neon = false },
			["Pommel"] = { color = "#E0393E", neon = false },
			["Fuller"] = { color = "#E0393E", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Runes"] = { color = "#E0393E", neon = false },
			["Wing_R"] = { color = "#E0393E", neon = false },
			["Wing_L"] = { color = "#E0393E", neon = false },
		} },
		primordial = { totalTris = 721, parts = {
			["Blade"] = { color = "#F4F2FA", neon = false },
			["Guard"] = { color = "#ECE8F6", neon = false },
			["Grip"] = { color = "#784682", neon = false },
			["Pommel"] = { color = "#ECE8F6", neon = false },
			["Fuller"] = { color = "#FF3CC8", neon = false },
			["Gem"] = { color = "#FFF4D6", neon = true },
			["Runes"] = { color = "#ECE8F6", neon = false },
			["Wing_R"] = { color = "#FF3CC8", neon = false },
			["Wing_L"] = { color = "#FF3CC8", neon = false },
			["Crystals"] = { color = "#FF3CC8", neon = true },
			["Halo"] = { color = "#FF3CC8", neon = true },
		} },
	},
}
