-- 자동 생성(roblox/tools/blender/meta_to_luau.py) - 손으로 고치지 말 것. 원본 = roblox/art/weapons/healer.meta.json
return {
	rigId = "healer", version = "A2-N2", pivot = "Grip",
	attachments = { Grip = { 0, 0, 0 }, Tip = { 0, 3.4, 0 }, Support = { 0, 1, 0 } },
	looks = {
		normal = { totalTris = 398, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#8C603A", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = false },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#706862", neon = false },
		} },
		legendary = { totalTris = 658, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#FF9933", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#FF9933", neon = false },
			["Band"] = { color = "#FF9933", neon = false },
		} },
		transcendent = { totalTris = 780, parts = {
			["Shaft"] = { color = "#262230", neon = false },
			["Head"] = { color = "#D6B03E", neon = false },
			["Orb"] = { color = "#FFD65A", neon = true },
			["Leaf"] = { color = "#D6B03E", neon = false },
			["Ferrule"] = { color = "#D6B03E", neon = false },
			["Band"] = { color = "#D6B03E", neon = false },
			["Runes"] = { color = "#D6B03E", neon = false },
			["Wing_R"] = { color = "#262230", neon = false },
			["Wing_L"] = { color = "#262230", neon = false },
			["Shards"] = { color = "#262230", neon = false },
			["Crack1"] = { color = "#FFD05C", neon = true },
		} },
		rare = { totalTris = 516, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#706862", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#706862", neon = false },
			["Bands"] = { color = "#4DA6FF", neon = false },
		} },
		epic = { totalTris = 666, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#A64DFF", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#A64DFF", neon = false },
			["Bands"] = { color = "#A64DFF", neon = false },
		} },
		relic = { totalTris = 634, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#FFD700", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#FFD700", neon = false },
			["Band"] = { color = "#FFD700", neon = false },
			["Runes"] = { color = "#FFD700", neon = true },
		} },
		ancient = { totalTris = 718, parts = {
			["Shaft"] = { color = "#684228", neon = false },
			["Head"] = { color = "#E0393E", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#E0393E", neon = false },
			["Band"] = { color = "#E0393E", neon = false },
			["Runes"] = { color = "#E0393E", neon = false },
			["Wing_R"] = { color = "#E0393E", neon = false },
			["Wing_L"] = { color = "#E0393E", neon = false },
		} },
		primordial = { totalTris = 793, parts = {
			["Shaft"] = { color = "#ECE2F0", neon = false },
			["Head"] = { color = "#ECE8F6", neon = false },
			["Orb"] = { color = "#8CF0C8", neon = true },
			["Leaf"] = { color = "#7EC446", neon = false },
			["Ferrule"] = { color = "#ECE8F6", neon = false },
			["Band"] = { color = "#FF3CC8", neon = false },
			["Runes"] = { color = "#ECE8F6", neon = false },
			["Wing_R"] = { color = "#FF3CC8", neon = false },
			["Wing_L"] = { color = "#FF3CC8", neon = false },
			["Crystals"] = { color = "#FF3CC8", neon = true },
			["Halo"] = { color = "#FF3CC8", neon = true },
		} },
	},
}
